/**
 * Opt-in scheduling + desktop notification for the welcome-back digest (B1 PR-2).
 *
 * Schedules ONLY the digest job (`seed digest --save [--notify]`) — never the
 * advanced autonomy tasks. Every subprocess goes through safe-exec argv form
 * (never a shell string). `seed digest --schedule` PRINTS the plan by default;
 * the system is mutated only behind an explicit `--install`. The crontab edit is
 * append-safe (a tagged block, backup-first) and reversible via `--unschedule`.
 */
import { writeFileSync, mkdirSync, existsSync, rmSync } from "fs";
import { join } from "path";
import { safeExec, commandExists } from "./safe-exec.ts";

export type Platform = "macos" | "linux" | "windows" | "unknown";

export const CRON_BEGIN = "# >>> digital-seed welcome digest >>>";
export const CRON_END = "# <<< digital-seed welcome digest <<<";
const LAUNCHD_LABEL = "com.digital-seed.welcome-digest";
const BUN = process.execPath;

export function detectPlatform(): Platform {
  if (process.platform === "darwin") return "macos";
  if (process.platform === "linux") return "linux";
  if (process.platform === "win32") return "windows";
  return "unknown";
}

/** Parse "HH:MM" → "M H * * *"; default / invalid → 09:00. */
export function digestCronExpr(hhmm?: string): string {
  const m = /^(\d{1,2}):(\d{2})$/.exec((hhmm ?? "").trim());
  let h = 9;
  let min = 0;
  if (m) {
    const hh = Number(m[1]);
    const mm = Number(m[2]);
    if (hh >= 0 && hh <= 23 && mm >= 0 && mm <= 59) {
      h = hh;
      min = mm;
    }
  }
  return `${min} ${h} * * *`;
}

function parseTime(hhmm?: string): { h: number; min: number } {
  const [min, h] = digestCronExpr(hhmm).split(" ");
  return { h: Number(h), min: Number(min) };
}

/** argv for the scheduled job — launchd uses this verbatim (no shell). */
export function digestCommand(root: string, opts: { notify?: boolean }): string[] {
  return [BUN, "run", join(root, "scripts/seed.ts"), "digest", "--save", ...(opts.notify ? ["--notify"] : [])];
}

function shellQuote(s: string): string {
  return `"${s.replace(/(["$`\\])/g, "\\$1")}"`;
}

/** A crontab line (cron runs commands via /bin/sh, so this is a quoted shell string). */
export function digestCronLine(root: string, opts: { notify?: boolean; time?: string }): string {
  const expr = digestCronExpr(opts.time);
  const cmd = digestCommand(root, opts).map(shellQuote).join(" ");
  const log = shellQuote(join(root, "logs/digests/schedule.log"));
  return `${expr} cd ${shellQuote(root)} && ${cmd} >> ${log} 2>&1`;
}

/** Escape XML text content so a path with & < > " ' can't forge plist structure or break the XML. */
function xmlEscape(s: string): string {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export function digestLaunchdPlist(root: string, opts: { notify?: boolean; time?: string }): string {
  const { h, min } = parseTime(opts.time);
  const args = digestCommand(root, opts)
    .map((a) => `    <string>${xmlEscape(a)}</string>`)
    .join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
${args}
  </array>
  <key>WorkingDirectory</key>
  <string>${xmlEscape(root)}</string>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key>
    <integer>${h}</integer>
    <key>Minute</key>
    <integer>${min}</integer>
  </dict>
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>`;
}

/** Remove our tagged block (and its markers) from a crontab body. */
export function stripCronBlock(crontab: string): string {
  const out: string[] = [];
  let inBlock = false;
  for (const line of crontab.split("\n")) {
    if (line.trim() === CRON_BEGIN) {
      inBlock = true;
      continue;
    }
    if (line.trim() === CRON_END) {
      inBlock = false;
      continue;
    }
    if (!inBlock) out.push(line);
  }
  return out.join("\n");
}

/** Merge our block into an existing crontab — append-safe, idempotent (replaces our prior block). */
export function mergeCronBlock(crontab: string, line: string): string {
  const base = stripCronBlock(crontab).replace(/\n+$/, "");
  const block = [
    CRON_BEGIN,
    "# Generated by `seed digest --schedule` — remove with `seed digest --unschedule`",
    line,
    CRON_END,
  ].join("\n");
  return (base ? base + "\n" : "") + block + "\n";
}

/** Strip control chars + quotes/backslashes so a notification payload can't break out of its argv/AppleScript string. */
function notifyText(s: string): string {
  // eslint-disable-next-line no-control-regex
  return String(s ?? "").replace(/[\x00-\x1f\x7f-\x9f"\\]/g, " ").slice(0, 200);
}

export function notifyCommand(platform: Platform, title: string, body: string): { cmd: string; argv: string[] } | null {
  const t = notifyText(title);
  const b = notifyText(body);
  if (platform === "linux") return { cmd: "notify-send", argv: [t, b] };
  if (platform === "macos") return { cmd: "osascript", argv: ["-e", `display notification "${b}" with title "${t}"`] };
  return null;
}

/** The printed recipe shown by `seed digest --schedule` (no system mutation). */
export function planText(root: string, opts: { notify?: boolean; time?: string }): string {
  const line = digestCronLine(root, opts);
  return [
    "To run your welcome digest automatically, you have two options.",
    "",
    "1) Let Digital Seed install it for you (recommended):",
    `   bun run seed digest --schedule ${opts.time ?? "09:00"}${opts.notify ? " --notify" : ""} --install`,
    "   (cron on Linux, launchd on macOS — append-safe; remove with `seed digest --unschedule`)",
    "",
    "2) Or add this cron line yourself (crontab -e):",
    "",
    `   ${line}`,
    "",
    "Nothing has been installed yet — this is just the plan.",
  ].join("\n");
}

// ── System mutation (explicit --install only; NOT exercised by unit tests) ──────

export interface ActionResult {
  ok: boolean;
  message: string;
}

function plistPath(): string {
  const home = process.env.HOME || "";
  return join(home, "Library", "LaunchAgents", `${LAUNCHD_LABEL}.plist`);
}

function installCron(root: string, opts: { notify?: boolean; time?: string }): ActionResult {
  if (!commandExists("crontab")) {
    return { ok: false, message: `\`crontab\` not found. Add this line manually (crontab -e):\n\n   ${digestCronLine(root, opts)}` };
  }
  const cur = safeExec("crontab", ["-l"]);
  const existing = cur.exitCode === 0 ? cur.stdout : ""; // non-zero = no crontab yet
  // Back up before touching it.
  try {
    const logs = join(root, "logs");
    mkdirSync(logs, { recursive: true });
    if (existing.trim()) writeFileSync(join(logs, "crontab.bak"), existing, "utf-8");
  } catch {
    /* best-effort backup */
  }
  const merged = mergeCronBlock(existing, digestCronLine(root, opts));
  const res = safeExec("crontab", ["-"], { input: merged });
  if (res.exitCode === 0) {
    return { ok: true, message: "✅ Scheduled. Inspect with `crontab -l`; remove with `seed digest --unschedule`." };
  }
  return { ok: false, message: `Could not write crontab (${res.stderr.trim() || "unknown error"}). Add it manually:\n\n   ${digestCronLine(root, opts)}` };
}

function installLaunchd(root: string, opts: { notify?: boolean; time?: string }): ActionResult {
  const path = plistPath();
  try {
    mkdirSync(join(path, ".."), { recursive: true });
    writeFileSync(path, digestLaunchdPlist(root, opts), "utf-8");
  } catch (e) {
    return { ok: false, message: `Could not write ${path}: ${(e as Error).message}` };
  }
  safeExec("launchctl", ["unload", path]); // ignore if not loaded
  const res = safeExec("launchctl", ["load", "-w", path]);
  if (res.exitCode === 0) {
    return { ok: true, message: `✅ Scheduled via launchd (${path}). Remove with \`seed digest --unschedule\`.` };
  }
  return { ok: false, message: `Wrote ${path} but \`launchctl load\` failed: ${res.stderr.trim() || "unknown error"}` };
}

export function installSchedule(root: string, opts: { notify?: boolean; time?: string }): ActionResult {
  const platform = detectPlatform();
  if (platform === "linux") return installCron(root, opts);
  if (platform === "macos") return installLaunchd(root, opts);
  return { ok: false, message: `Automatic install isn't supported on "${platform}". Use the cron line from \`seed digest --schedule\`.` };
}

export function uninstallSchedule(root: string): ActionResult {
  const platform = detectPlatform();
  if (platform === "macos") {
    const path = plistPath();
    if (!existsSync(path)) return { ok: true, message: "Nothing scheduled (no launchd job)." };
    safeExec("launchctl", ["unload", path]);
    try {
      rmSync(path);
    } catch {
      /* already gone */
    }
    return { ok: true, message: "✅ Unscheduled (launchd job removed)." };
  }
  if (platform === "linux") {
    if (!commandExists("crontab")) return { ok: false, message: "`crontab` not found." };
    const cur = safeExec("crontab", ["-l"]);
    if (cur.exitCode !== 0) return { ok: true, message: "Nothing scheduled (no crontab)." };
    if (!cur.stdout.includes(CRON_BEGIN)) return { ok: true, message: "Nothing scheduled (no digest block)." };
    const res = safeExec("crontab", ["-"], { input: stripCronBlock(cur.stdout).replace(/\n+$/, "") + "\n" });
    return res.exitCode === 0
      ? { ok: true, message: "✅ Unscheduled (crontab block removed)." }
      : { ok: false, message: `Could not update crontab: ${res.stderr.trim() || "unknown error"}` };
  }
  return { ok: true, message: `Nothing to do on "${platform}".` };
}

/** Best-effort desktop notification — never throws, never fails the calling command. */
export function sendNotification(title: string, body: string): ActionResult {
  const platform = detectPlatform();
  const cmd = notifyCommand(platform, title, body);
  if (!cmd) return { ok: false, message: `(desktop notifications aren't supported on "${platform}")` };
  if (!commandExists(cmd.cmd)) {
    return { ok: false, message: `(skipped desktop notification — \`${cmd.cmd}\` not installed)` };
  }
  try {
    const res = safeExec(cmd.cmd, cmd.argv, { timeout: 5000 });
    return res.exitCode === 0
      ? { ok: true, message: "🔔 Desktop notification sent." }
      : { ok: false, message: `(desktop notification failed: ${res.stderr.trim() || "non-zero exit"})` };
  } catch (e) {
    return { ok: false, message: `(desktop notification error: ${(e as Error).message})` };
  }
}
